# The docker compose file to create a postgres instance.
#docker-compose --build
#docker-compose up

# Example
#docker-compose up --build
#docker-compose up

# Create .env file and modify before each docker compose up.
# in .env file
#POSTGRES_USER=[YOUR_USERNAME]
#POSTGRES_PASSWORD=[YOUR_USERNAME]
#POSTGRES_DB=[YOUR_DB_NAME]
#PORT_NUMBER=[YOUR_PORT_NUMBER]

#This docker-compose file is linked to the Dockerfile.

services:
  postgres:
    build:
      context: .
    restart: always
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PORT_NUMBER}:5432"