#-------------------------------------------------------------
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
#-------------------------------------------------------------


name: Docker Image CI and CD

on:
  schedule:
    - cron: '0 12 * * *' # everyday at 6:00 PM UTC
  workflow_dispatch:
  

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: return01/systemds
        tags: |
          type=schedule,pattern=nightly

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
## Uncomment the following to inspect buildx build
# 
#     - name: Inspect builder
#       run: |
#           echo "Name:      ${{ steps.buildx.outputs.name }}"
#           echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
#           echo "Status:    ${{ steps.buildx.outputs.status }}"
#           echo "Flags:     ${{ steps.buildx.outputs.flags }}"
#           echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

    # IMPORTANT: The credentials should not be available via the
    # Pull request, hence this if condition here.
    # github.event_name != 'pull_request'
    - name: Login to DockerHub
#       if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    # https://github.com/docker/build-push-action
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/sysds.Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
